Name:           ros-indigo-sql-database
Version:        0.4.9
Release:        0%{?dist}
Summary:        ROS sql_database package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/database_interface
Source0:        %{name}-%{version}.tar.gz

Requires:       derelict-postgresql-devel
Requires:       postgresql-devel
Requires:       ros-indigo-roscpp
Requires:       yaml-cpp-devel
BuildRequires:  derelict-postgresql-devel
BuildRequires:  pkgconfig
BuildRequires:  postgresql-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roscpp
BuildRequires:  yaml-cpp-devel

%description
Provides an easy to use and general interface between a SQL database and object-
oriented C++ code, making it easy to encapsulate the conceptual
&quot;objects&quot; contained in the database as C++ classes.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Matei Ciocarlie <matei.ciocarlie@gmail.com> - 0.4.9-0
- Autogenerated by Bloom

